# Generated by Django 3.2.5 on 2021-07-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='California', max_length=100)),
                ('charging_type', models.CharField(default='Level 2', max_length=20)),
                ('charging', models.BooleanField(default=False)),
                ('peak', models.BooleanField(default=True)),
                ('set_charge_threshold', models.IntegerField(default=30)),
                ('current_charge', models.IntegerField(default=23)),
            ],
        ),
    ]
