# Generated by Django 3.2.5 on 2021-07-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charging',
            old_name='set_charge_threshold',
            new_name='charge_threshold',
        ),
    ]
