# Generated by Django 3.2.5 on 2021-07-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_rename_temperature_climate_temperature_f'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climate',
            old_name='temperature_f',
            new_name='current_temperature_f',
        ),
        migrations.AddField(
            model_name='climate',
            name='set_temperature_f',
            field=models.IntegerField(default=0),
        ),
    ]
