# Generated by Django 3.2.5 on 2021-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0003_auto_20210711_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='climate',
            name='cooling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='climate',
            name='heating',
            field=models.BooleanField(default=False),
        ),
    ]
