# Generated by Django 3.2.5 on 2021-07-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0004_auto_20210712_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='climate',
            name='outside_temperature_f',
            field=models.IntegerField(default=93),
        ),
    ]
